### ISSUE TITLE
哥们，我也做了一个进程通讯的框架，但是我只解决了异步通讯的问题，没解决同步通讯的问题

### ISSUE THREAD

**Issue by fanqieVip** [a3349384/EasyMessenger#1]
如题，希望能和你加好友探讨一下
https://github.com/fanqieVip/processroute
邮箱：810343451@qq.com

**Comment by a3349384** [comment]
同步通讯的难点主要在于如何同步拿到Server的Binder，目前Android上Server可以通过ContentProvider提供Binder，这样Client是可以同步拿到Server的Binder的。不过ContentProvider有个很大的缺点是其onCreate会在Application#onCreate之前被系统调用，这在实际项目上会导致很麻烦的问题。

**Comment by fanqieVip** [comment]
太感激了，虽然你说的后面一段我不是太明白（对ContentProvider不太了解），但至少帮助我提供了一个思路，再次表示感谢

**Comment by a3349384** [comment]
@fanqieVip 举个例子，比如A进程想要向B进程发起IPC通信请求，但这时B进程还没有启动。这时，通过向B进程的ContentProvider查询Binder是可以做到同步的，但是该ContentProvider会在B进程的Application#onCreate之前被创建。

在实际项目中，我们会在Application中做很多业务的初始化工作，在这些初始化工作没做好之前，冒然向B进程发起IPC请求很容易导致异常。

**Comment by fanqieVip** [comment]
我有些明白你的意思了，就是B进程还没有初始化完成，这时候我使用ContentProvider远程call进程B取一个数据，而这个数据可能是依赖于B初始化完成后才会产生，于是问题就产生了。是不是类似这种意思啊？

**Comment by a3349384** [comment]
> 我有些明白你的意思了，就是B进程还没有初始化完成，这时候我使用ContentProvider远程call进程B取一个数据，而这个数据可能是依赖于B初始化完成后才会产生，于是问题就产生了。是不是类似这种意思啊？

是的，就是这意思

**Comment by fanqieVip** [comment]
好吧，既然这样的话，确实不适合做成跨进程通讯的同步方案。因为跨进程数据共享更多的还是处理持久化数据，我还是单独使用网友开源的跨进程数据同步方案吧，也就不集成到我那个库了。今天又长知识了，谢谢老哥
